[package]
name = "solarsystem_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
rust_utils = {path = "../rust_utils"}

[profile.dev]
opt-level = 3
