[package]
name = "solarsystem_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.8.0"
im = "15.1.0"
# bevy = "0.9.1"
macroquad = "0.3.25"
itertools = "0.10.5"
